-- Persist tool confirmations so decisions survive process restarts.
create table if not exists public.agent_tool_confirmations (
  id bigint generated by default as identity primary key,
  user_id text not null,
  session_id text not null,
  tool_call_id text not null,
  approved boolean not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_agent_tool_confirmations_identity unique (user_id, session_id, tool_call_id)
);

create index if not exists idx_agent_tool_confirmations_expires_at
  on public.agent_tool_confirmations (expires_at);

create or replace function public.touch_agent_tool_confirmations_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_touch_agent_tool_confirmations_updated_at
  on public.agent_tool_confirmations;

create trigger trg_touch_agent_tool_confirmations_updated_at
before update on public.agent_tool_confirmations
for each row
execute function public.touch_agent_tool_confirmations_updated_at();
